// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/cart.ts";
import * as $$$1 from "./loaders/product/productDetailsPage.ts";
import * as $$$2 from "./loaders/product/productList.ts";
import * as $$$$$$$$$0 from "./actions/cart/addItems.ts";
import * as $$$$$$$$$1 from "./actions/cart/updateItem.ts";

const manifest = {
  "loaders": {
    "salesforce/loaders/cart.ts": $$$0,
    "salesforce/loaders/product/productDetailsPage.ts": $$$1,
    "salesforce/loaders/product/productList.ts": $$$2,
  },
  "actions": {
    "salesforce/actions/cart/addItems.ts": $$$$$$$$$0,
    "salesforce/actions/cart/updateItem.ts": $$$$$$$$$1,
  },
  "name": "salesforce",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
